AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
    StageName:
        Type: String
        Default: '$default'

Resources:
    handlerFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: src/handlers/handler.handler
            Runtime: nodejs14.x
            MemorySize: 128
            Timeout: 100
            Events:
                ApiGet:
                    Type: HttpApi
                    Properties:
                        Path: /
                        Method: GET
                ApiOptions:
                    Type: HttpApi
                    Properties:
                        Path: /
                        Method: OPTIONS

    HttpApi:
        Type: AWS::Serverless::HttpApi
        Properties:
            FailOnWarnings: true
            CorsConfiguration:
                AllowOrigins:
                    - "*"
                AllowHeaders:
                    - "*"
                AllowMethods:
                    - "*"
                MaxAge: 600
                AllowCredentials: false

Outputs:
    HttpApiUrl:
        Description: HTTP API End point
        Value:
            Fn::Sub: 'https://${HttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/'
        Export:
            Name: !Sub "${AWS::StackName}-HttpAPI"
    HttpApiId:
        Description: HTTP API ID
        Value:
            Fn::Sub: '${HttpApi}'
        Export:
            Name: !Sub "${AWS::StackName}-HttpAPIID"
