AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
    StageName:
        Type: String
        Default: '$default'

Resources:
    handlerFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: src/handlers/handler.handler
            Runtime: nodejs14.x
            MemorySize: 128
            Timeout: 100
            Events:
                ApiGet:
                    Type: HttpApi
                    Properties:
                        ApiId: !Ref HttpApi
                        Path: /
                        Method: GET
                ApiOptions:
                    Type: HttpApi
                    Properties:
                        ApiId: !Ref HttpApi
                        Path: /
                        Method: OPTIONS

    HttpApi:
        Type: AWS::Serverless::HttpApi
        Properties:
            FailOnWarnings: true
        StageName: !Ref StageName
            CorsConfiguration:
                AllowOrigins:
                    - "https://example.com"
                AllowHeaders:
                    - x-apigateway-header
                AllowMethods:
                    - GET
                MaxAge: 600
                AllowCredentials: true
            DefinitionBody: |
                openapi: "3.0.1"
                paths: {}
                x-amazon-apigateway-cors:
                    allowOrigins:
                      - '*'
                    allowHeaders:
                      - '*'
                    allowCredentials: false
                    maxAge: 600
                    allowMethods:
                      - '*'

Outputs:
    HttpApiUrl:
        Description: HTTP API End point
        Value:
            Fn::Sub: 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/'
        Export:
            Name: !Sub "${AWS::StackName}-HttpAPI"
    HttpApiId:
        Description: HTTP API ID
        Value:
            Fn::Sub: '${ServerlessHttpApi}'
        Export:
            Name: !Sub "${AWS::StackName}-HttpAPIID"
